source "https://rubygems.org"

gem "fastlane"
gem "google-cloud-storage" # required by firebase_app_distribution plugin

plugins_path = File.join(File.dirname(__FILE__), "fastlane", "Pluginfile")
eval_gemfile(plugins_path) if File.exist?(plugins_path)
