// ignore_for_file: uri_has_not_been_generated
// ^ app_database.g.dart is generated by build_runner. Run:
//   dart run build_runner build
// before analyzing or building. The generated file is gitignored.

import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:sqlite3_flutter_libs/sqlite3_flutter_libs.dart';

part 'app_database.g.dart';

// Tables will be added here as features are built out.
// Planned schema: courses, sections, blocks, video metadata, sync state.

// Tables will be added here as features are built. Pending schema:
// courses, sections, blocks, video metadata, sync state.
@DriftDatabase()
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  // ignore: override_on_non_overriding_member
  int get schemaVersion => 1;
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    await applyWorkaroundToOpenSqlite3OnOldAndroidVersions();

    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'emajtee.db'));
    return NativeDatabase.createInBackground(file);
  });
}
