// ^ app_database.g.dart is generated by build_runner. Run:
//   dart run build_runner build
// before analyzing or building. The generated file is gitignored.

import 'dart:convert';
import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:sqlite3_flutter_libs/sqlite3_flutter_libs.dart';

part 'app_database.g.dart';

// JSON blob cache tables — one per API response type, keyed by natural ID.
// Mirrors the web app's Dexie cache strategy.

class CachedEnrollments extends Table {
  TextColumn get key => text()();
  TextColumn get data => text()();
  DateTimeColumn get cachedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {key};
}

class CachedOutlines extends Table {
  TextColumn get courseId => text()();
  TextColumn get data => text()();
  DateTimeColumn get cachedAt => dateTime()();
  TextColumn get etag => text().nullable()();
  TextColumn get lastModified => text().nullable()();

  @override
  Set<Column> get primaryKey => {courseId};
}

class CachedSequences extends Table {
  TextColumn get blockId => text()();
  TextColumn get data => text()();
  DateTimeColumn get cachedAt => dateTime()();
  TextColumn get etag => text().nullable()();
  TextColumn get lastModified => text().nullable()();

  @override
  Set<Column> get primaryKey => {blockId};
}

class CachedXblocks extends Table {
  TextColumn get blockId => text()();
  TextColumn get data => text()();
  DateTimeColumn get cachedAt => dateTime()();
  TextColumn get etag => text().nullable()();
  TextColumn get lastModified => text().nullable()();

  @override
  Set<Column> get primaryKey => {blockId};
}

/// Derived cache of sanitized HTML computed from [CachedXblocks]. Rebuildable
/// from the source xblock rows, so we drop this on every schema upgrade.
/// [sanitizerVersion] lets us invalidate rows whose HTML was produced by a
/// previous sanitizer revision — see `kSanitizerVersion` in `xblock_parser.dart`.
class CachedSanitizedXblocks extends Table {
  TextColumn get blockId => text()();
  TextColumn get safeHtml => text()();
  IntColumn get sanitizerVersion => integer()();
  DateTimeColumn get cachedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {blockId};
}

/// Persists the last-synced timestamp and last error per course.
/// The in-memory sync status (idle/syncing) lives in `SyncController` only.
class CachedCourseSync extends Table {
  TextColumn get courseId => text()();
  DateTimeColumn get lastSyncedAt => dateTime().nullable()();
  TextColumn get lastError => text().nullable()();

  @override
  Set<Column> get primaryKey => {courseId};
}

/// Persists the last-synced timestamp and last error per lecture
/// (sequence block). Mirrors [CachedCourseSync] but at sequence granularity so
/// the outline UI can render each lecture's "synced / not synced / error"
/// state correctly after an app restart. The in-memory sync status
/// (idle/syncing/scheduled) lives in `SyncManagerState` only.
class CachedLectureSync extends Table {
  TextColumn get sequenceId => text()();
  TextColumn get courseId => text()();
  DateTimeColumn get lastSyncedAt => dateTime().nullable()();
  TextColumn get lastError => text().nullable()();

  @override
  Set<Column> get primaryKey => {sequenceId};
}

/// User state: which lists the user has opted to sync. Presence of a row means
/// selected. Persists across schema upgrades like [DownloadedVideos].
/// [listId] is a synthetic id: `"all-enrolled"` for the system list, otherwise
/// the upstream learn.mit.edu userlist id as a string.
class SelectedLists extends Table {
  TextColumn get listId => text()();
  TextColumn get source => text()(); // 'enrolled' | 'learn_my_list'
  TextColumn get name => text()();
  DateTimeColumn get selectedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {listId};
}

/// Cache of the list-of-lists shown in the picker. Rebuildable from the
/// mitxonline + learn.mit.edu APIs; dropped on schema upgrade like other
/// caches. [totalCourseCount] includes unsupported (OCW etc.) courses.
class AvailableLists extends Table {
  TextColumn get listId => text()();
  TextColumn get source => text()();
  TextColumn get name => text()();
  IntColumn get totalCourseCount => integer()();
  DateTimeColumn get fetchedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {listId};
}

/// User state: ref-counted mapping of locally-cached courses to the selected
/// lists that pulled them in. A course with no rows here is in the drop set
/// and will be fully removed on reconciliation. Persists across schema
/// upgrades.
class CourseListMemberships extends Table {
  TextColumn get courseId => text()();
  TextColumn get listId => text()();

  @override
  Set<Column> get primaryKey => {courseId, listId};
}

/// Cache of list items we CAN'T sync (edX etc.) but still want to display on
/// the home screen so the user knows they're in a selected list even though
/// we can't download them yet. Rebuilt on every reconciliation — safe to
/// treat as cache.
///
/// [courseId] is the resource's `readable_id` (stable-ish across runs) since
/// unsupported items don't have an Open edX courseware_id.
class UnsupportedListItems extends Table {
  TextColumn get courseId => text()();
  TextColumn get listId => text()();
  TextColumn get title => text()();
  TextColumn get platformCode => text()();

  @override
  Set<Column> get primaryKey => {courseId, listId};
}

/// Cache of OCW course metadata. One row per course.
/// [courseId] is `"ocw:{slug}"` (see opencourseware-support.md).
class CachedOcwCourses extends Table {
  TextColumn get courseId => text()();
  TextColumn get slug => text()();
  TextColumn get title => text()();
  TextColumn get courseNumber => text()();
  TextColumn get description => text()();

  /// Absolute URL of the course hero image (from `<meta property="og:image">`).
  TextColumn get imageUrl => text().nullable()();

  DateTimeColumn get cachedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {courseId};
}

/// Cache of OCW lectures. Each lecture belongs to a course and (in v1) a single
/// synthetic "Video Lectures" section. [mp4Url] is null for YouTube-only
/// lectures and "in-class dissection" entries that have no downloadable video.
class CachedOcwLectures extends Table {
  TextColumn get lectureId => text()();
  TextColumn get courseId => text()();
  TextColumn get slug => text()();
  TextColumn get title => text()();
  TextColumn get sectionTitle => text()();
  IntColumn get sectionOrder => integer()();
  IntColumn get lectureOrder => integer()();
  TextColumn get mp4Url => text().nullable()();
  IntColumn get durationSeconds => integer().nullable()();
  DateTimeColumn get cachedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {lectureId};
}

/// Cache of OCW downloadable resources (PDF lecture notes / slides).
/// [lectureId] null means this resource couldn't be matched to a lecture and
/// is surfaced at course level.
class CachedOcwResources extends Table {
  TextColumn get resourceId => text()();
  TextColumn get courseId => text()();
  TextColumn get lectureId => text().nullable()();
  TextColumn get type => text()(); // OcwResourceType enum name
  TextColumn get title => text()();
  TextColumn get url => text()();
  DateTimeColumn get cachedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {resourceId};
}

/// User state: one row per course tracking the user's last-played lecture
/// and position. Preserved across schema upgrades (never in [_cacheTables]).
///
/// [lectureId] is polymorphic by course type:
///   - MITx courses (courseId = `course-v1:...`): sequence block id
///     (e.g. `block-v1:MITxT+...+type@sequential+block@...`).
///   - OCW courses (courseId = `ocw:...`): `CachedOcwLectures.lectureId`.
class CoursePositions extends Table {
  TextColumn get courseId => text()();
  TextColumn get lectureId => text()();
  RealColumn get positionSeconds => real()();
  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {courseId};
}

/// Tracks downloaded + rescaled course artwork files on disk. Keyed by remote
/// URL so MITx and OCW share one dedup pool (shared URLs → shared file).
/// User state: preserved across schema upgrades (files on disk).
class CourseImages extends Table {
  TextColumn get url => text()();
  TextColumn get localFilePath => text()();
  DateTimeColumn get downloadedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {url};
}

/// Tracks downloaded video files on disk. Primary key is the video URL —
/// deduplication is URL-keyed so a video shared across courses is only
/// downloaded once. [courseIds] is a JSON-encoded `List<String>`.
class DownloadedVideos extends Table {
  TextColumn get url => text()();
  TextColumn get localFilePath => text()();
  TextColumn get courseIds => text()(); // JSON List<String>
  TextColumn get status => text()(); // DownloadStatus.name
  RealColumn get progress =>
      real().withDefault(const Constant<double>(0))();
  IntColumn get bytesDownloaded =>
      integer().withDefault(const Constant(0))();
  IntColumn get totalBytes =>
      integer().withDefault(const Constant(0))();
  // background_downloader task ID (SHA1 of URL) — used for cancel
  TextColumn get taskId => text().nullable()();
  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {url};
}

// Cache table names used in migration (must match actual table names).
// These are dropped and recreated on every schema upgrade — user state tables
// (selected_lists, course_list_memberships, downloaded_videos) are preserved.
const _cacheTables = [
  'cached_enrollments',
  'cached_outlines',
  'cached_sequences',
  'cached_xblocks',
  'cached_sanitized_xblocks',
  'cached_course_sync',
  'available_lists',
  'unsupported_list_items',
  'cached_ocw_courses',
  'cached_ocw_lectures',
  'cached_ocw_resources',
];

@DriftDatabase(tables: [
  CachedEnrollments,
  CachedOutlines,
  CachedSequences,
  CachedXblocks,
  CachedSanitizedXblocks,
  CachedCourseSync,
  CachedLectureSync,
  DownloadedVideos,
  CourseImages,
  SelectedLists,
  AvailableLists,
  CourseListMemberships,
  UnsupportedListItems,
  CachedOcwCourses,
  CachedOcwLectures,
  CachedOcwResources,
  CoursePositions,
])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  /// Test constructor. Use with `NativeDatabase.memory()` to get an in-memory
  /// DB for unit tests.
  AppDatabase.forTesting(super.executor);

  @override
  int get schemaVersion => 12;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) => m.createAll(),
        onUpgrade: (m, from, to) async {
          // Drop and recreate only the cache tables (they are rebuildable from
          // the server). NEVER drop downloaded_videos — it references files on
          // disk and is user data.
          await m.recreateAllViews();
          for (final tableName in _cacheTables) {
            await m.deleteTable(tableName);
          }
          // Create any tables that don't yet exist (including downloaded_videos
          // on first upgrade to schema v4).
          await m.createAll();
        },
      );

  // --- Enrollments (singleton row with key = 'enrollments') ---

  Future<({String data, DateTime cachedAt})?> getEnrollments() async {
    final row = await (select(cachedEnrollments)
          ..where((t) => t.key.equals('enrollments')))
        .getSingleOrNull();
    if (row == null) return null;
    return (data: row.data, cachedAt: row.cachedAt);
  }

  Future<void> putEnrollments(String json) => into(cachedEnrollments).insertOnConflictUpdate(
        CachedEnrollmentsCompanion.insert(
          key: 'enrollments',
          data: json,
          cachedAt: DateTime.now(),
        ),
      );

  // --- Outlines (keyed by courseId) ---

  Future<({String data, DateTime cachedAt, String? etag, String? lastModified})?>
      getOutline(String courseId) async {
    final row = await (select(cachedOutlines)
          ..where((t) => t.courseId.equals(courseId)))
        .getSingleOrNull();
    if (row == null) return null;
    return (
      data: row.data,
      cachedAt: row.cachedAt,
      etag: row.etag,
      lastModified: row.lastModified,
    );
  }

  Future<void> putOutline(
    String courseId,
    String json, {
    String? etag,
    String? lastModified,
  }) =>
      into(cachedOutlines).insertOnConflictUpdate(
        CachedOutlinesCompanion.insert(
          courseId: courseId,
          data: json,
          cachedAt: DateTime.now(),
          etag: Value(etag),
          lastModified: Value(lastModified),
        ),
      );

  // --- Sequences (keyed by blockId) ---

  Future<({String data, DateTime cachedAt, String? etag, String? lastModified})?>
      getSequence(String blockId) async {
    final row = await (select(cachedSequences)
          ..where((t) => t.blockId.equals(blockId)))
        .getSingleOrNull();
    if (row == null) return null;
    return (
      data: row.data,
      cachedAt: row.cachedAt,
      etag: row.etag,
      lastModified: row.lastModified,
    );
  }

  Future<void> putSequence(
    String blockId,
    String json, {
    String? etag,
    String? lastModified,
  }) =>
      into(cachedSequences).insertOnConflictUpdate(
        CachedSequencesCompanion.insert(
          blockId: blockId,
          data: json,
          cachedAt: DateTime.now(),
          etag: Value(etag),
          lastModified: Value(lastModified),
        ),
      );

  // --- Xblocks (keyed by blockId) ---

  Future<({String data, DateTime cachedAt, String? etag, String? lastModified})?>
      getXblock(String blockId) async {
    final row = await (select(cachedXblocks)
          ..where((t) => t.blockId.equals(blockId)))
        .getSingleOrNull();
    if (row == null) return null;
    return (
      data: row.data,
      cachedAt: row.cachedAt,
      etag: row.etag,
      lastModified: row.lastModified,
    );
  }

  Future<void> putXblock(
    String blockId,
    String json, {
    String? etag,
    String? lastModified,
  }) =>
      into(cachedXblocks).insertOnConflictUpdate(
        CachedXblocksCompanion.insert(
          blockId: blockId,
          data: json,
          cachedAt: DateTime.now(),
          etag: Value(etag),
          lastModified: Value(lastModified),
        ),
      );

  // --- Sanitized Xblocks (keyed by blockId) ---

  Future<CachedSanitizedXblock?> getSanitizedXblock(String blockId) =>
      (select(cachedSanitizedXblocks)
            ..where((t) => t.blockId.equals(blockId)))
          .getSingleOrNull();

  Future<void> putSanitizedXblock({
    required String blockId,
    required String safeHtml,
    required int sanitizerVersion,
  }) =>
      into(cachedSanitizedXblocks).insertOnConflictUpdate(
        CachedSanitizedXblocksCompanion.insert(
          blockId: blockId,
          safeHtml: safeHtml,
          sanitizerVersion: sanitizerVersion,
          cachedAt: DateTime.now(),
        ),
      );

  // --- Course sync state (keyed by courseId) ---

  Future<({DateTime? lastSyncedAt, String? lastError})?> getSyncState(
    String courseId,
  ) async {
    final row = await (select(cachedCourseSync)
          ..where((t) => t.courseId.equals(courseId)))
        .getSingleOrNull();
    if (row == null) return null;
    return (lastSyncedAt: row.lastSyncedAt, lastError: row.lastError);
  }

  /// Records a successful sync. Clears any previous error.
  Future<void> putSyncSuccess(String courseId, DateTime lastSyncedAt) =>
      into(cachedCourseSync).insertOnConflictUpdate(
        CachedCourseSyncCompanion.insert(
          courseId: courseId,
          lastSyncedAt: Value(lastSyncedAt),
          lastError: const Value(null),
        ),
      );

  /// Records a sync error. Preserves lastSyncedAt from the previous success.
  Future<void> putSyncError(String courseId, String error) =>
      into(cachedCourseSync).insertOnConflictUpdate(
        CachedCourseSyncCompanion(
          courseId: Value(courseId),
          lastError: Value(error),
        ),
      );

  /// Returns every row in [cachedCourseSync]. Used at sync-isolate startup to
  /// hydrate the in-memory `SyncManagerState` so the UI shows persisted
  /// "synced <time> ago" / error state immediately after app restart.
  Future<List<CachedCourseSyncData>> getAllCourseSyncState() =>
      select(cachedCourseSync).get();

  // --- Lecture sync state (keyed by sequenceId) ---

  Future<({DateTime? lastSyncedAt, String? lastError})?> getLectureSyncState(
    String sequenceId,
  ) async {
    final row = await (select(cachedLectureSync)
          ..where((t) => t.sequenceId.equals(sequenceId)))
        .getSingleOrNull();
    if (row == null) return null;
    return (lastSyncedAt: row.lastSyncedAt, lastError: row.lastError);
  }

  /// Returns every row in [cachedLectureSync]. Used at sync-isolate startup
  /// to hydrate per-lecture scope state.
  Future<List<CachedLectureSyncData>> getAllLectureSyncState() =>
      select(cachedLectureSync).get();

  /// Records a successful lecture sync. Clears any previous error.
  Future<void> putLectureSyncSuccess(
    String sequenceId,
    String courseId,
    DateTime lastSyncedAt,
  ) =>
      into(cachedLectureSync).insertOnConflictUpdate(
        CachedLectureSyncCompanion.insert(
          sequenceId: sequenceId,
          courseId: courseId,
          lastSyncedAt: Value(lastSyncedAt),
          lastError: const Value(null),
        ),
      );

  /// Records a lecture sync error. Preserves lastSyncedAt from the previous
  /// success so a partial failure doesn't roll the lecture back to "never
  /// synced".
  Future<void> putLectureSyncError(
    String sequenceId,
    String courseId,
    String error,
  ) =>
      into(cachedLectureSync).insertOnConflictUpdate(
        CachedLectureSyncCompanion.insert(
          sequenceId: sequenceId,
          courseId: courseId,
          lastError: Value(error),
        ),
      );

  /// Clears all lecture sync rows for a course. Called from
  /// [deleteCourseCache] so dropped courses don't leave orphan rows.
  Future<void> deleteLectureSyncForCourse(String courseId) =>
      (delete(cachedLectureSync)
            ..where((t) => t.courseId.equals(courseId)))
          .go();

  // --- Downloaded Videos ---

  Future<DownloadedVideo?> getDownloadedVideo(String url) =>
      (select(downloadedVideos)..where((t) => t.url.equals(url)))
          .getSingleOrNull();

  Stream<DownloadedVideo?> watchDownloadedVideo(String url) =>
      (select(downloadedVideos)..where((t) => t.url.equals(url)))
          .watchSingleOrNull();

  Stream<List<DownloadedVideo>> watchDownloadsForUrls(List<String> urls) {
    if (urls.isEmpty) return Stream.value([]);
    return (select(downloadedVideos)..where((t) => t.url.isIn(urls))).watch();
  }

  Future<List<DownloadedVideo>> getAllDownloadedVideos() =>
      select(downloadedVideos).get();

  Future<List<DownloadedVideo>> getDownloadsForCourse(String courseId) =>
      (select(downloadedVideos)
            ..where((t) => t.courseIds.contains(courseId)))
          .get();

  Future<void> upsertDownloadedVideo(DownloadedVideosCompanion companion) =>
      into(downloadedVideos).insertOnConflictUpdate(companion);

  Future<void> updateDownloadProgress(
    String url, {
    required double progress,
    required int bytesDownloaded,
    required int totalBytes,
  }) =>
      (update(downloadedVideos)..where((t) => t.url.equals(url))).write(
        DownloadedVideosCompanion(
          status: const Value('downloading'),
          progress: Value(progress),
          bytesDownloaded: Value(bytesDownloaded),
          totalBytes: Value(totalBytes),
          updatedAt: Value(DateTime.now()),
        ),
      );

  Future<void> markDownloadComplete(String url, String localFilePath) =>
      (update(downloadedVideos)..where((t) => t.url.equals(url))).write(
        DownloadedVideosCompanion(
          localFilePath: Value(localFilePath),
          status: const Value('downloaded'),
          progress: const Value<double>(1),
          updatedAt: Value(DateTime.now()),
        ),
      );

  Future<void> markDownloadFailed(String url) =>
      (update(downloadedVideos)..where((t) => t.url.equals(url))).write(
        DownloadedVideosCompanion(
          status: const Value('failed'),
          updatedAt: Value(DateTime.now()),
        ),
      );

  Future<void> markDownloadQueued(String url) =>
      (update(downloadedVideos)..where((t) => t.url.equals(url))).write(
        DownloadedVideosCompanion(
          status: const Value('queued'),
          updatedAt: Value(DateTime.now()),
        ),
      );

  Future<void> markDownloadStale(String url) =>
      (update(downloadedVideos)..where((t) => t.url.equals(url))).write(
        DownloadedVideosCompanion(
          status: const Value('stale'),
          updatedAt: Value(DateTime.now()),
        ),
      );

  Future<void> deleteDownloadedVideo(String url) =>
      (delete(downloadedVideos)..where((t) => t.url.equals(url))).go();

  /// Removes [courseId] from the row's courseIds list. If no courses remain,
  /// deletes the row entirely and returns the localFilePath for the caller
  /// to delete from disk.
  Future<String?> removeCourseFromDownload(String url, String courseId) async {
    final row = await getDownloadedVideo(url);
    if (row == null) return null;

    final ids = (jsonDecode(row.courseIds) as List<dynamic>)
        .cast<String>()
        .where((id) => id != courseId)
        .toList();

    if (ids.isEmpty) {
      await deleteDownloadedVideo(url);
      return row.localFilePath;
    }

    await (update(downloadedVideos)..where((t) => t.url.equals(url))).write(
      DownloadedVideosCompanion(courseIds: Value(jsonEncode(ids))),
    );
    return null;
  }

  // --- Selected lists (user state) ---

  Future<List<SelectedList>> getSelectedLists() =>
      select(selectedLists).get();

  Stream<List<SelectedList>> watchSelectedLists() =>
      select(selectedLists).watch();

  /// Transactionally replaces the entire selection with [lists]. Rows whose
  /// [SelectedList.listId] no longer appear are deleted; new ones are inserted.
  /// Existing rows are updated in place (preserves `selectedAt` when unchanged).
  Future<void> replaceSelectedLists(List<SelectedListsCompanion> lists) =>
      transaction(() async {
        await delete(selectedLists).go();
        for (final row in lists) {
          await into(selectedLists).insert(row);
        }
      });

  // --- Available lists (cache) ---

  Future<List<AvailableList>> getAvailableLists() =>
      select(availableLists).get();

  Stream<List<AvailableList>> watchAvailableLists() =>
      select(availableLists).watch();

  /// Transactionally replaces the cached list-of-lists with [lists]. Always a
  /// full refresh so a deleted upstream list disappears from the cache.
  Future<void> replaceAvailableLists(List<AvailableListsCompanion> lists) =>
      transaction(() async {
        await delete(availableLists).go();
        for (final row in lists) {
          await into(availableLists).insert(row);
        }
      });

  // --- Course list memberships (user state, ref-counted) ---

  /// Returns all courseIds that appear in at least one currently-selected list.
  Future<Set<String>> getCourseIdsInSelection() async {
    final rows = await (selectOnly(courseListMemberships, distinct: true)
          ..addColumns([courseListMemberships.courseId]))
        .get();
    return rows
        .map((r) => r.read(courseListMemberships.courseId)!)
        .toSet();
  }

  /// Rebuild memberships for a single list: delete all existing rows for
  /// [listId], then insert one per courseId in [courseIds]. Transactional so
  /// a reconciliation can be retried cleanly.
  Future<void> rebuildMembershipForList(
    String listId,
    Iterable<String> courseIds,
  ) =>
      transaction(() async {
        await (delete(courseListMemberships)
              ..where((t) => t.listId.equals(listId)))
            .go();
        for (final courseId in courseIds) {
          await into(courseListMemberships).insert(
            CourseListMembershipsCompanion.insert(
              courseId: courseId,
              listId: listId,
            ),
          );
        }
      });

  /// Rebuild cached unsupported items for a single list. Pairs with
  /// [rebuildMembershipForList] so home can display OCW / edX items with a
  /// "not yet supported" badge without trying to sync them.
  Future<void> rebuildUnsupportedForList(
    String listId,
    Iterable<UnsupportedListItemsCompanion> items,
  ) =>
      transaction(() async {
        await (delete(unsupportedListItems)
              ..where((t) => t.listId.equals(listId)))
            .go();
        for (final row in items) {
          await into(unsupportedListItems).insert(row);
        }
      });

  /// Deletes membership and unsupported-item rows for any list whose
  /// `listId` isn't in [keepListIds] — i.e. lists the user has removed from
  /// selection. Without this pruning, [getCoursesNotInSelection] still sees
  /// dropped lists' courses as "in selection" and never schedules them for
  /// drop-cascade, so their downloaded videos linger on disk.
  Future<void> pruneOrphanListData(Set<String> keepListIds) =>
      transaction(() async {
        if (keepListIds.isEmpty) {
          await delete(courseListMemberships).go();
          await delete(unsupportedListItems).go();
          return;
        }
        await (delete(courseListMemberships)
              ..where((t) => t.listId.isNotIn(keepListIds)))
            .go();
        await (delete(unsupportedListItems)
              ..where((t) => t.listId.isNotIn(keepListIds)))
            .go();
      });

  Stream<List<UnsupportedListItem>> watchUnsupportedListItems() =>
      select(unsupportedListItems).watch();

  /// Returns courseIds that have local state (outline, sync record, or downloads)
  /// but are no longer referenced by any selected-list membership — the "drop
  /// set" for reconciliation.
  Future<Set<String>> getCoursesNotInSelection() async {
    final inSelection = await getCourseIdsInSelection();

    final known = <String>{};
    final outlineRows =
        await (selectOnly(cachedOutlines)..addColumns([cachedOutlines.courseId]))
            .get();
    for (final r in outlineRows) {
      known.add(r.read(cachedOutlines.courseId)!);
    }
    final syncRows = await (selectOnly(cachedCourseSync)
          ..addColumns([cachedCourseSync.courseId]))
        .get();
    for (final r in syncRows) {
      known.add(r.read(cachedCourseSync.courseId)!);
    }
    final lectureSyncRows = await (selectOnly(cachedLectureSync, distinct: true)
          ..addColumns([cachedLectureSync.courseId]))
        .get();
    for (final r in lectureSyncRows) {
      known.add(r.read(cachedLectureSync.courseId)!);
    }
    final ocwRows = await (selectOnly(cachedOcwCourses)
          ..addColumns([cachedOcwCourses.courseId]))
        .get();
    for (final r in ocwRows) {
      known.add(r.read(cachedOcwCourses.courseId)!);
    }

    return known.difference(inSelection);
  }

  /// Removes all rows for [courseId] from sync/cache tables (excluding
  /// downloaded_videos — the downloads layer handles those). Safe to call
  /// even if nothing exists.
  Future<void> deleteCourseCache(String courseId) => transaction(() async {
        await (delete(cachedCourseSync)
              ..where((t) => t.courseId.equals(courseId)))
            .go();
        await (delete(cachedLectureSync)
              ..where((t) => t.courseId.equals(courseId)))
            .go();
        await (delete(cachedOutlines)
              ..where((t) => t.courseId.equals(courseId)))
            .go();
        // Sequences/xblocks/sanitized are keyed by blockId, not courseId —
        // they get cleared via `clearLmsCache()` or remain until a general
        // cache flush. Course-scoped cleanup of block-keyed tables would
        // require knowing the block ids; the existing sync pipeline already
        // handles stale blocks on next run.
        await (delete(courseListMemberships)
              ..where((t) => t.courseId.equals(courseId)))
            .go();
        // OCW cache tables are courseId-keyed so we can clean them eagerly.
        // For non-OCW courseIds these deletes are no-ops.
        await (delete(cachedOcwCourses)
              ..where((t) => t.courseId.equals(courseId)))
            .go();
        await (delete(cachedOcwLectures)
              ..where((t) => t.courseId.equals(courseId)))
            .go();
        await (delete(cachedOcwResources)
              ..where((t) => t.courseId.equals(courseId)))
            .go();
        await (delete(coursePositions)
              ..where((t) => t.courseId.equals(courseId)))
            .go();
      });

  // --- OCW course cache ---

  Future<CachedOcwCourse?> getOcwCourse(String courseId) =>
      (select(cachedOcwCourses)..where((t) => t.courseId.equals(courseId)))
          .getSingleOrNull();

  Stream<CachedOcwCourse?> watchOcwCourse(String courseId) =>
      (select(cachedOcwCourses)..where((t) => t.courseId.equals(courseId)))
          .watchSingleOrNull();

  Future<List<CachedOcwLecture>> getOcwLectures(String courseId) =>
      (select(cachedOcwLectures)
            ..where((t) => t.courseId.equals(courseId))
            ..orderBy([
              (t) => OrderingTerm(expression: t.sectionOrder),
              (t) => OrderingTerm(expression: t.lectureOrder),
            ]))
          .get();

  Future<CachedOcwLecture?> getOcwLecture(String lectureId) =>
      (select(cachedOcwLectures)..where((t) => t.lectureId.equals(lectureId)))
          .getSingleOrNull();

  Future<List<CachedOcwResource>> getOcwResources(String courseId) =>
      (select(cachedOcwResources)
            ..where((t) => t.courseId.equals(courseId)))
          .get();

  Future<List<CachedOcwResource>> getOrphanOcwResources(String courseId) =>
      (select(cachedOcwResources)
            ..where((t) =>
                t.courseId.equals(courseId) & t.lectureId.isNull()))
          .get();

  Future<List<String>> getOcwLectureMp4Urls(String courseId) async {
    final rows = await (selectOnly(cachedOcwLectures)
          ..addColumns([cachedOcwLectures.mp4Url])
          ..where(cachedOcwLectures.courseId.equals(courseId) &
              cachedOcwLectures.mp4Url.isNotNull()))
        .get();
    return rows
        .map((r) => r.read(cachedOcwLectures.mp4Url))
        .whereType<String>()
        .toList();
  }

  /// Transactional full-replace of an OCW course and its lectures + resources.
  /// Removes any rows for this courseId that aren't in the new set.
  Future<void> replaceOcwCourse({
    required CachedOcwCoursesCompanion course,
    required List<CachedOcwLecturesCompanion> lectures,
    required List<CachedOcwResourcesCompanion> resources,
  }) =>
      transaction(() async {
        final courseId = course.courseId.value;
        await (delete(cachedOcwResources)
              ..where((t) => t.courseId.equals(courseId)))
            .go();
        await (delete(cachedOcwLectures)
              ..where((t) => t.courseId.equals(courseId)))
            .go();
        await into(cachedOcwCourses).insertOnConflictUpdate(course);
        for (final lec in lectures) {
          await into(cachedOcwLectures).insert(lec);
        }
        for (final res in resources) {
          await into(cachedOcwResources).insert(res);
        }
      });

  // --- Course images (user state) ---

  Future<CourseImage?> getCourseImage(String url) =>
      (select(courseImages)..where((t) => t.url.equals(url)))
          .getSingleOrNull();

  /// Reactive: emits the latest [CourseImage] row for [url] or null when
  /// missing. Used by the home-screen tiles so artwork renders the instant
  /// the downloader inserts the row.
  Stream<CourseImage?> watchCourseImage(String url) =>
      (select(courseImages)..where((t) => t.url.equals(url)))
          .watchSingleOrNull();

  Future<void> upsertCourseImage({
    required String url,
    required String localFilePath,
  }) =>
      into(courseImages).insertOnConflictUpdate(
        CourseImagesCompanion.insert(
          url: url,
          localFilePath: localFilePath,
          downloadedAt: DateTime.now(),
        ),
      );

  Future<void> deleteCourseImage(String url) =>
      (delete(courseImages)..where((t) => t.url.equals(url))).go();

  // --- Course positions (user state) ---

  Future<CoursePosition?> getCoursePosition(String courseId) =>
      (select(coursePositions)..where((t) => t.courseId.equals(courseId)))
          .getSingleOrNull();

  Stream<CoursePosition?> watchCoursePosition(String courseId) =>
      (select(coursePositions)..where((t) => t.courseId.equals(courseId)))
          .watchSingleOrNull();

  Future<void> upsertCoursePosition({
    required String courseId,
    required String lectureId,
    required double positionSeconds,
  }) =>
      into(coursePositions).insertOnConflictUpdate(
        CoursePositionsCompanion.insert(
          courseId: courseId,
          lectureId: lectureId,
          positionSeconds: positionSeconds,
          updatedAt: DateTime.now(),
        ),
      );

  Future<void> deleteCoursePosition(String courseId) =>
      (delete(coursePositions)..where((t) => t.courseId.equals(courseId))).go();

  // --- Data-usage helpers ---

  /// Returns the absolute path to the SQLite database file. Can be called
  /// before the database is opened (useful for computing file size).
  static Future<String> dbFilePath() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    return p.join(dbFolder.path, 'emajtee.db');
  }

  /// Sum of the on-disk size of every file for a `downloaded` row.
  ///
  /// We stat the files directly rather than trusting the `bytes_downloaded`
  /// column: `background_downloader` only populates that column from progress
  /// callbacks, which rely on the server advertising `Content-Length`. When
  /// the CDN omits that header (or the final progress tick reports
  /// `expectedFileSize <= 0`) the column stays at 0 even though the file
  /// downloaded fine, making the data-usage screen report ~1 KB for users
  /// who had gigabytes of video cached.
  Future<int> getTotalDownloadedBytes() async {
    final rows = await (select(downloadedVideos)
          ..where((t) => t.status.equals('downloaded')))
        .get();
    var total = 0;
    for (final row in rows) {
      if (row.localFilePath.isEmpty) continue;
      try {
        final file = File(row.localFilePath);
        if (file.existsSync()) total += await file.length();
      } on Object catch (_) {
        // Missing/unreadable file — skip it.
      }
    }
    return total;
  }

  /// Clears only the [DownloadedVideos] table and returns the local file paths
  /// so the caller can delete the files from disk.
  Future<List<String>> clearDownloadedVideosAndGetPaths() async {
    final rows = await getAllDownloadedVideos();
    final paths = rows
        .where((r) => r.localFilePath.isNotEmpty)
        .map((r) => r.localFilePath)
        .toList();
    await delete(downloadedVideos).go();
    return paths;
  }

  // --- Clear LMS-side caches (used after fresh LMS auth to discard any
  //     content fetched while unauthenticated). Leaves enrollments and
  //     downloaded videos intact. ---

  Future<void> clearLmsCache() async {
    await delete(cachedOutlines).go();
    await delete(cachedSequences).go();
    await delete(cachedXblocks).go();
    await delete(cachedSanitizedXblocks).go();
    await delete(cachedOcwCourses).go();
    await delete(cachedOcwLectures).go();
    await delete(cachedOcwResources).go();
  }

  // --- Clear all cached data (used on sign-out).
  //     Caller must also delete files for the rows returned here. ---

  Future<List<String>> clearAllAndGetDownloadPaths() async {
    final rows = await getAllDownloadedVideos();
    final paths = rows
        .where((r) => r.localFilePath.isNotEmpty)
        .map((r) => r.localFilePath)
        .toList();
    await delete(downloadedVideos).go();
    await delete(cachedEnrollments).go();
    await delete(cachedOutlines).go();
    await delete(cachedSequences).go();
    await delete(cachedXblocks).go();
    await delete(cachedSanitizedXblocks).go();
    await delete(cachedCourseSync).go();
    await delete(cachedLectureSync).go();
    await delete(selectedLists).go();
    await delete(availableLists).go();
    await delete(courseListMemberships).go();
    await delete(unsupportedListItems).go();
    await delete(cachedOcwCourses).go();
    await delete(cachedOcwLectures).go();
    await delete(cachedOcwResources).go();
    await delete(coursePositions).go();
    return paths;
  }

  // Keep the old clearAll for any callers that don't need the paths.
  Future<void> clearAll() async {
    await clearAllAndGetDownloadPaths();
  }
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    await applyWorkaroundToOpenSqlite3OnOldAndroidVersions();
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'emajtee.db'));
    return NativeDatabase.createInBackground(
      file,
      // WAL lets the main and sync isolates open independent connections
      // to the same file without blocking each other on simple reads;
      // busy_timeout makes the writer wait for the lock instead of
      // failing immediately with SQLITE_BUSY when both isolates commit
      // concurrently. synchronous=NORMAL is the documented safe setting
      // under WAL (FULL is for rollback journals).
      setup: (db) {
        db
          ..execute('PRAGMA journal_mode = WAL')
          ..execute('PRAGMA synchronous = NORMAL')
          ..execute('PRAGMA busy_timeout = 5000');
      },
    );
  });
}
